kind: ConfigMap
apiVersion: v1
metadata:
  name: mysql-config
  namespace: etherpad
  labels:
    app: mysql
    layer: db
    project: etherpad
data:
  MYSQL_ROOT_PASSWORD: "toor"
  MYSQL_DATABASE: "etherpad_lite_db"
  MYSQL_USER: "etherpad"
  MYSQL_PASSWORD: "etherpad"
  MYSQL_PORT: "3306"
