kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-volume-claim
  namespace: etherpad
  labels:
    app: mysql
    layer: storage
    project: etherpad
spec:
  # storageClassName: nfs-client-storage-class
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
